version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: billiard_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billiard_db
      MYSQL_USER: billiard
      MYSQL_PASSWORD: billiard1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

